### PR TITLE
gzclient launcher updated with gpu option and test results included

### PR DESCRIPTION
**Pull request by lu164**
I have tested gzclient using GPU and added the results in the folder "/tmp/gpu test results", I have also included in the results folder the used commands.

The RTF has improved from 0.8 to 0.9 and FPS from 12.41 to 62.61.

### CODE REVIEW

**Comment by jmplaza** [comment]
Great result @lu164 !

Watch out there are many py cache files on your PR. In addition the figures could be uploaded to your TFG repository instead of this one.... They are part of a measurement, not source code...

**Comment by lu164** [comment]
Hi @jmplaza ! I have removed the test results folder but i am not sure which pycache files are you referring, those that are deleted?

**Comment by jmplaza** [comment]
You are right @lu164, no problem with the deleted files. 

This modified PR is ready to be reviewed by another developer. @Blancasr could you review it?

**Comment by Blancasr** [comment]
Of course, I'll make some testing

**Pull request merged**
